# 4장 
## 신경망

#### 1. OR 데이터 인식

In [1]:
from sklearn.linear_model import Perceptron

# 훈련 집합 구축
x = [[0,0],[0,1],[1,0],[1,1]]
y = [-1,1,1,1]

# fit 함수로 Perceptron 학습
p = Perceptron()
p.fit(x,y)

print("학습된 퍼셉트론의 매개 변수",p.coef_,p.intercept_)
print("훈련집합에 대한 예측",p.predict(x))
print("정확률 측정 : ",p.score(x,y)*100,"%")

학습된 퍼셉트론의 매개 변수 [[2. 2.]] [-1.]
훈련집합에 대한 예측 [-1  1  1  1]
정확률 측정 :  100.0 %


### 2. 필기 숫자 데이터 인식

In [3]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import numpy as np

# 데이터 셋을 읽고 훈련 집합과 테스트 집합으로 분할
digit = datasets.load_digits()
x_train,x_test,y_train,y_test = train_test_split(digit.data,digit.target,train_size=0.6)

# fit 함수로 Perceptron 학습
p = Perceptron(max_iter=100,eta0=0.001,verbose=0)
p.fit(x_train,y_train) #digit 테이터로 모벨링

res = p.predict(x_test) # 테스트 집합으로 예측

# 혼동 행렬
conf = np.zeros((10,10))

for i in range(len(res)):
    conf[res[i]][y_test[i]]+=1
print(conf)

# 정확률 계산
no_correct = 0
for i in range(10):
    no_correct += conf[i][i]
accuracy = no_correct/len(res)
print("테스트 집합에 대한 정확률 = ",accuracy*100,"% 입니다.")

[[77.  1.  0.  1.  0.  0.  2.  0.  0.  0.]
 [ 0. 65.  2.  2.  8.  1.  0.  0. 14.  1.]
 [ 0.  0. 73.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 58.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 64.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  3.  0. 63.  0.  0.  1.  2.]
 [ 0.  1.  0.  0.  1.  1. 78.  0.  8.  0.]
 [ 0.  0.  0.  2.  1.  1.  0. 61.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0. 52.  0.]
 [ 0.  0.  0.  2.  1.  2.  0.  1.  0. 65.]]
테스트 집합에 대한 정확률 =  91.23783031988873 % 입니다.


### sklearn 의 필기 숫자 데이터셋

In [4]:
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import numpy as np

# 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
digit = datasets.load_digits()
x_train,x_test,y_train,y_test = train_test_split(digit.data,digit.target,train_size=0.6)

#MPL 분류기 모델을 학습
mlp = MLPClassifier(hidden_layer_sizes=(100),learning_rate_init=0.001,batch_size=32,max_iter=300,solver='sgd',verbose=True)
mlp.fit(x_train,y_train)

res = mlp.predict(x_test) # 테스트 집합으로 예측

#혼동 행렬
conf = np.zeros((10,10))
for i in range(len(res)):
    conf[res[i]][y_test[i]]+=1
print(conf)

# 정확률 계산
no_correct=0
for i in range(10):
    no_correct+=conf[i][i]
accuracy = no_correct/len(res)
print("테스트 집합에 대한 정확률은 ",accuracy*100,"% 입니다.")

Iteration 1, loss = 2.40106973
Iteration 2, loss = 0.33804648
Iteration 3, loss = 0.21880686
Iteration 4, loss = 0.16270003
Iteration 5, loss = 0.13463516
Iteration 6, loss = 0.11396073
Iteration 7, loss = 0.10043825
Iteration 8, loss = 0.08871727
Iteration 9, loss = 0.08036757
Iteration 10, loss = 0.07125316
Iteration 11, loss = 0.06510181
Iteration 12, loss = 0.05999661
Iteration 13, loss = 0.05758024
Iteration 14, loss = 0.05253436
Iteration 15, loss = 0.04735516
Iteration 16, loss = 0.04316002
Iteration 17, loss = 0.04025942
Iteration 18, loss = 0.03939235
Iteration 19, loss = 0.03523740
Iteration 20, loss = 0.03324584
Iteration 21, loss = 0.03102449
Iteration 22, loss = 0.02981767
Iteration 23, loss = 0.02795935
Iteration 24, loss = 0.02677000
Iteration 25, loss = 0.02622434
Iteration 26, loss = 0.02411722
Iteration 27, loss = 0.02347740
Iteration 28, loss = 0.02235018
Iteration 29, loss = 0.02207299
Iteration 30, loss = 0.02072914
Iteration 31, loss = 0.01964497
Iteration 32, los

### MNIST 데이터셋으로 확장하기

In [7]:
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt
import numpy as np

# MNIST 데이터셋을 읽고 훈련 집합과 테스트 집합으로 분할
mnist = fetch_openml('mnist_784')
mnist.data = mnist.data/255.0
x_train = mnist.data[:60000]; x_test=mnist.data[60000:]
y_train = np.int16(mnist.target[:60000]); y_test = np.int16(mnist.target[60000:])

#MPL 분류기 모델을 학습
mlp = MLPClassifier(hidden_layer_sizes=(100),learning_rate_init=0.001,batch_size=512,max_iter=300,solver='adam',verbose=True)
mlp.fit(x_train,y_train)

# 테스트 집합으로 예측
res = mlp.predict(x_test)

#혼동 행렬
conf = np.zeros((10,10),dtype=np.int16)
for i in range(len(res)):
    conf[res[i]][y_test[i]]+=1
print(conf)

# 정확률 계산
no_correct=0
for i in range(10):
    no_correct+=conf[i][i]
accuracy = no_correct/len(res)
print("테스트 집합에 대한 정확률은",accuracy*100,"% 입니다.")

Iteration 1, loss = 0.60850820
Iteration 2, loss = 0.27047413
Iteration 3, loss = 0.21904079
Iteration 4, loss = 0.18441040
Iteration 5, loss = 0.15890209
Iteration 6, loss = 0.13872661
Iteration 7, loss = 0.12234523
Iteration 8, loss = 0.10853985
Iteration 9, loss = 0.09777905
Iteration 10, loss = 0.08836896
Iteration 11, loss = 0.08030759
Iteration 12, loss = 0.07335521
Iteration 13, loss = 0.06736680
Iteration 14, loss = 0.06214992
Iteration 15, loss = 0.05726335
Iteration 16, loss = 0.05355107
Iteration 17, loss = 0.04936703
Iteration 18, loss = 0.04587349
Iteration 19, loss = 0.04280114
Iteration 20, loss = 0.03946514
Iteration 21, loss = 0.03652675
Iteration 22, loss = 0.03481748
Iteration 23, loss = 0.03189138
Iteration 24, loss = 0.03004875
Iteration 25, loss = 0.02808042
Iteration 26, loss = 0.02613918
Iteration 27, loss = 0.02407635
Iteration 28, loss = 0.02246562
Iteration 29, loss = 0.02140110
Iteration 30, loss = 0.01949004
Iteration 31, loss = 0.01852007
Iteration 32, los

### 4.5 은닉 노드 개수 찾기

In [1]:
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split,validation_curve
import numpy as np
import time

#
digit = datasets.load_digits()
x_train,x_test,y_train,y_test = train_test_split(digit.data,digit.target,train_size=0.6)


#
strat = time.time()
mlp = MLPClassifier(learning_rate_init=0.001,batch_size=32,max_iter=300,solver='sqd')
prange = range(50,1001,50)
train_score,test_score =validation_curve(mlp,x_train,y_train,param_name="hidden_layer_size",param_range=prange,cv = 10,scoring="accuracy",n_jobs=4)
end = time.time()
print("하이퍼 매개변수 최적화에 걸린 시간은",end-strat,"초 입니다.")

#
train_mean = np.mean(train_score,axis=1)
train_std = np.std(train_score,axis=1)
test_mean = np.mean(test_score,axis=1)
test_std = np.std(test_score,axis=1)

#
plt.plot(prange,train_mean,label="Train score",color = "r")
plt.plot(prange,test_mean,label="Test score",color="b")
plt.fill_between(prange,train_mean-train_std,train_mean+train_std,alpha=0.2,color="r")
plt.fill_between(prange,test_mean-test_std,test_mean+test_std,alpha=0.2,color="b")
plt.legend(loc="best")
plt.title("Validation Curve with MLP")
plt.xlabel("Number of hidden nodes");plt.ylabel("Accuracy")
plt.ylim(0.9,1.01)
plt.grid(axis='both')
plt.show()

best_number_nodes = prange[np.argmax(test_mean)]
print("\n 최적의 노드 개수",best_number_nodes," 개 입니다.\n")

#
mlp_test = MLPClassifier(hidden_layer_sizes=(best_number_nodes),learning_rate_init=0.001,batch_size=32,max_iter=300,solver='sgd')
mlp_test.fit(x_train,y_train)

#
res = mlp_test.predict(x_test)

#
conf = np.zeros((10,10))
for i in range(len(res)):
    conf[res[i][y_test[i]]]+=1
print(conf)

#
no_correct = 0
for i in range(10):
    no_correct+=conf[i][i]
accuracy = no_correct/len(res)
print("정확률은",accuracy*100," 입니다.")


ValueError: Invalid parameter hidden_layer_size for estimator MLPClassifier(batch_size=32, max_iter=300, solver='sqd'). Check the list of available parameters with `estimator.get_params().keys()`.